name: CRUD

on:
  push:
    branches:
      - main

jobs:
  build_and_crud:

    runs-on: ubuntu-latest

    steps:
    - name: Revisar Repositorio
      uses: actions/checkout@v2

    - name: Ejecutar CRUD
      run: |
        .Trabajo_final/crud_script.sh
